Repository AY2324S1-CS2103T-T14-4/tp, pull requests merged in 2023-10, with the labels that each got.

#49 Update site-wide settings
  docs/_markbind/layouts/default.md
  docs/site.json
  docs/team/brein62.md
  docs/team/zacwong2151.md
Labels: documentation, priority.Medium

#71 Edit remaining documentation details
  docs/AboutUs.md
  docs/images/ruo-x.png
  docs/images/zacwong2151.png
  docs/index.md
Labels: documentation, priority.High

#80 Add create, list, delete volunteer use cases for DG
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#87 Change URL for UG in help menu
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: enhancement, priority.Low

#90 Implement vcreate, vlist, vdelete features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/volunteercommandparsers/VolunteerEditCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedVolunteer.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditVolunteerDescriptorTest.java
  src/test/java/seedu/address/logic/commands/VolunteerEditCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/VolunteerCreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/VolunteerEditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/volunteer/UniqueVolunteerListTest.java
  src/test/java/seedu/address/model/volunteer/VolunteerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVolunteerTest.java
  src/test/java/seedu/address/testutil/TypicalVolunteers.java
Labels: enhancement, type.Story, priority.High

#91 Finalise UG and DG to reflect v1.2 changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#93 Implement create event feature test cases
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/eventcommands/EventCreateCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/eventcommandparsers/EventCreateCommandParser.java
  src/main/java/seedu/address/model/event/Budget.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/Description.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Location.java
  src/main/java/seedu/address/model/event/Material.java
  src/main/java/seedu/address/model/event/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonEventStorage.java
  src/main/java/seedu/address/storage/JsonVolunteerStorage.java
  src/main/java/seedu/address/storage/event/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/event/JsonAdaptedMaterial.java
  src/main/java/seedu/address/storage/event/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/event/JsonSerializableEventStorage.java
  src/main/java/seedu/address/storage/volunteer/JsonAdaptedSkill.java
  src/main/java/seedu/address/storage/volunteer/JsonAdaptedVolunteer.java
  src/main/java/seedu/address/storage/volunteer/JsonSerializableVolunteerStorage.java
  src/main/java/seedu/address/ui/EventCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EventCreateCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EventCreateCommandTest.java
  src/test/java/seedu/address/logic/parser/EventCreateCommandParserTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVolunteerTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: enhancement, priority.Medium

#85 Implement parsing of arguments for create event feature
  src/main/java/seedu/address/logic/parser/eventcommandparsers/EventCreateCommandParser.java
  src/main/java/seedu/address/model/event/EventName.java
Labels: enhancement, priority.High

#97 build.gradle: Enable assertions
  build.gradle
Labels: priority.Low

#98 Add end date/time to Event
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/eventcommands/EventCreateCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/eventcommandparsers/EventCreateCommandParser.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/storage/event/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventWindowCard.java
  src/main/resources/view/EventWindowCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EventCreateCommandParserTest.java
  src/test/java/seedu/address/model/event/EventNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/storage/event/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/volunteer/JsonAdaptedVolunteerTest.java
  src/test/java/seedu/address/storage/volunteer/JsonSerializableVolunteerStorageTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: enhancement, priority.Medium

#110 Set up v1.2.1 trial release
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: priority.Low

#103 Update UG for vfind feature
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerFindCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/volunteercommandparsers/VolunteerCreateCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparsers/VolunteerEditCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparsers/VolunteerFindCommandParser.java
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/volunteer/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/volunteer/SkillNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/VolunteerFindCommandTest.java
  src/test/java/seedu/address/logic/parser/IVolunteerParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/VolunteerFindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/volunteer/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/volunteer/SkillNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalVolunteers.java
Labels: enhancement, priority.Medium

#114 Update DG for material and role track feature
  docs/DeveloperGuide.md
  docs/diagrams/QuantityClassDiagram.puml
Labels: documentation, priority.Medium

#108 Change label formatting for skills, roles, materials
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/VolunteerCard.java
  src/main/java/seedu/address/ui/labels/EnclosedLabel.java
  src/main/java/seedu/address/ui/labels/LabelColors.java
  src/main/java/seedu/address/ui/labels/MaterialLabel.java
  src/main/java/seedu/address/ui/labels/RoleLabel.java
  src/main/java/seedu/address/ui/labels/SkillLabel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EnclosedLabel.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/VolunteerListCard.fxml
Labels: enhancement, priority.Medium

#109 Add quantity fields to Material
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/eventcommands/EventAddMaterialCommand.java
  src/main/java/seedu/address/logic/parser/IVolunteerParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/eventcommandparsers/EventAddMaterialCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Material.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/event/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/event/JsonAdaptedMaterial.java
  src/main/java/seedu/address/ui/EventWindowCard.java
  src/main/java/seedu/address/ui/labels/MaterialLabel.java
  src/main/resources/view/EventShowWindow.fxml
  src/main/resources/view/EventWindowCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EventAddMaterialCommandTest.java
  src/test/java/seedu/address/logic/parser/EventAddMaterialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IVolunteerParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/MaterialTest.java
  src/test/java/seedu/address/storage/event/JsonAdaptedEventTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: enhancement, type.Story, priority.High
