Repository AY2324S1-CS2103T-T14-4/tp, pull requests merged in 2023-11, with the labels that each got.

#129 Fix Event and Volunteer to make them immutable
  src/main/java/seedu/address/logic/commands/eventvolunteercommands/EventAddVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/eventvolunteercommands/EventRemoveVolunteerCommand.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/volunteer/Volunteer.java
  src/test/java/seedu/address/logic/commands/EventAddVolunteerCommandTest.java
Labels: bug, priority.High

#133 Update eedit to add current role quantity depending on volunteers in event
  src/main/java/seedu/address/logic/commands/eventcommands/EventEditCommand.java
Labels: bug, priority.Medium

#141 Fix ecreate bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug, priority.High

#195 Fix message usages for commands
  src/main/java/seedu/address/logic/commands/eventcommands/EventCreateCommand.java
Labels: priority.Medium, type.functionalityBug

#213 Update PPP for v1.4: Brendan
  docs/team/brein62.md
Labels: documentation, priority.High

#208 Fix bug where current role quantities are not updated after vedit
  src/main/java/seedu/address/logic/commands/eventcommands/EventEditCommand.java
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerEditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/EventCreateCommandTest.java
  src/test/java/seedu/address/logic/commands/VolunteerCreateCommandTest.java
Labels: priority.High, type.functionalityBug

#214 Update DG for iVolunteer
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EventAddVolunteerActivityDiagram.puml
  docs/diagrams/EventClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/QuantityClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/styleFields.puml
Labels: documentation, priority.High

#203 Add documentation for the feature eedit in the user guide
  docs/UserGuide.md
Labels: bug, documentation

#228 Improve logging and clean up project
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EnclosedLabel.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventWindowCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/VolunteerListCard.fxml
Labels: priority.Low

#205 Update Role and Material to better detect duplicates
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.featureFlaw

#202 Change eventStorage and volunteerStorage json files
  data/eventStorage.json
  data/volunteerStorage.json
Labels: priority.Medium, type.functionalityBug

#229 Update DG: Add use cases.
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#221 Remove the ability to edit event name field for eedit feature
  src/main/java/seedu/address/logic/commands/eventcommands/EventEditCommand.java
  src/main/java/seedu/address/logic/parser/eventcommandparsers/EventEditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEventDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EventDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EventEditCommandTest.java
  src/test/java/seedu/address/logic/parser/EventEditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventUtil.java
Labels: enhancement, priority.Low

#237 Add instructions for manual testing in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#242 Fix more PE bugs for UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.documentationBug

#230 Update PPP for v1.4: Max
  docs/team/tiongmax.md
Labels: documentation, priority.High

#234 Update DG: Add implementation details for edelete and eedit features and planned enhancements
  docs/DeveloperGuide.md
  docs/diagrams/EventDeleteActivityDiagram.puml
  docs/diagrams/EventDeleteSequenceDiagram.puml
  docs/diagrams/EventEditSequenceDiagram.puml
  docs/diagrams/VolunteerDeleteSequenceDiagram.puml
Labels: documentation, priority.High

#245 Remove functionality to edit volunteer name
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerEditCommand.java
  src/main/java/seedu/address/logic/parser/volunteercommandparsers/VolunteerEditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditVolunteerDescriptorTest.java
  src/test/java/seedu/address/logic/commands/VolunteerEditCommandTest.java
  src/test/java/seedu/address/logic/parser/VolunteerEditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditVolunteerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/VolunteerUtil.java
Labels: priority.High, type.functionalityBug
